### ISSUE TITLE
Enhanced? Solution for 2021/10

### ISSUE THREAD

**Issue by NimVek** [mebeim/aoc#12]
In Part2 you iterate over the stack to get a value for result.
You can cast the stack as an integer, like following:

`int(''.join(stack).translate(str.maketrans(')]}>', '1234'))[::-1], 5)`

maybe its not good readable, so it not might be enhanced

**Comment by mebeim** [comment]
Thanks you the suggestion. Yep that's a way to do it since numbers are in base 5. I had already tried this for myself earlier today. Problem is, it doesn't really have any performance benefit and it's a lot less readable/understandable, so I just decided to keep my solution as is.
