### ISSUE TITLE
Method name is incorrect in 2019 day 18 write-up.

### ISSUE THREAD

**Issue by SSteve** [mebeim/aoc#13]
After "Here's the updated function:" in the 2019 Day 18 write-up, the method name is still `minimum_steps` but should be `explore`.

Thanks so much for doing these write-ups. They are a generous contribution to the AoC community. When I get stuck on an advanced problem I always know I'll learn something by coming here.

**Comment by mebeim** [comment]
Thank you @SSteve I will fix this with the next batch of typo fixes, and thanks for the kind words too :)

**Comment by mebeim** [comment]
Fixed in e5c259096df5fac7ed28c030667106ddf25916d0.
