### ISSUE TITLE
2021 Day 22 code

### ISSUE THREAD

**Issue by atkinew0** [mebeim/aoc#14]
I tried to implement this code below for Part2 and found it did not work for me. I had to compute the intersections for both positive and negative without mutating the lists in the middle of the loop(i.e. by keeping new_positive and new_negative lists and appending them to positive and negative at the bottom of the main loop). I apologize if I have misunderstood your code/Python and thanks so much for your excellent walkthroughs.

```python
positive = []
negative = []

for on, cuboid in commands:
    for other in positive:
        inter = intersection(cuboid, other)
        if inter is None:
            continue

        negative.append(inter)

    for other in negative:
        inter = intersection(cuboid, other)
        if inter is None:
            continue

        positive.append(inter)

    if on:
        positive.append(cuboid)
```

**Comment by mebeim** [comment]
> I had to compute the intersections for both positive and negative without mutating the lists in the middle of the loop

You're completely right, the first inner loop `for other in positive` adds intersections to `negative`, but then when iterating with `for other in negative` those intersections are counted again, which is wrong. I did not notice this error when initially writing the walkthrough, thanks for pointing it out.

Your solution of using `new_positive` and `new_negative` list works, though you only need `new_negative` really, for the `positive` list there should be no issue. I'll fix my walkthrough right away. Thanks again :)

**Comment by atkinew0** [comment]
Ah I see, I didn't check it only for negative space only but that makes
sense to me now. Thanks for checking that. You're walkthrough were a huge
help for me this year.
