### ISSUE TITLE
Typo in 24/2022 solution

### ISSUE THREAD

**Issue by Manitary** [mebeim/aoc#17]
Noticed a typo [here](https://github.com/mebeim/aoc/blob/20d47b6ee024ac0bd236dc679a7ea76aad743501/2022/solutions/day24.py#L71): the second bfs stores the updated blizzard as ``blitz`` instead of ``bliz``, so it is not passed to the third bfs.

**Comment by mebeim** [comment]
Thank you! Fixed in 92bcb00710bf65f7afe9bbe7ca9b6d9e428d8048. I really had to fight hard with my brain to avoid typing `blitz` instead of `bliz` for all those variables :')
