### ISSUE TITLE
keep it up !

### ISSUE THREAD

**Issue by edelans** [mebeim/aoc#3]
Hello @mebeim , 

Your repo has become my go to place once I complete my challenge of the day (it used to be reddit, then I saw your repo there, and I switched my habbit instantly : I :heart: your walkthrough, you manage to add a lot of value to the code, with plenty of references (docs, wikipedia, general knowledge...) that help me expand my knowledge more efficiently than reading dry code lines on reddit. 

I was surprised not to find your solution today, so I though I would send you some thankfulness =) : just in case you are wondering if the efforts your are putting in on a daily basis are worth it, I can tell you that there is at least one person who cares =). I have that (working) ugly part2 that needs fixing https://github.com/edelans/aoc2020/blob/master/day16.py : I'm looking forward to read yours.

Keep it up !

**Comment by mebeim** [comment]
Hey @edelans, thank you very much for the kind words, I'm flattered! Really glad that you are enjoying the walkthroughs 😄 Some days I don't have much free time so walkthroughs can get delayed, but no worries, I'll eventually write and publish them. I've just pushed today's walkthrough (wrote it kind of in a hurry so excuse any typo/inaccuracy, those will get eventually fixed later anyway). 

Thanks again and happy reading!

**Comment by edelans** [comment]
Hello @mebeim, just passing by to say thanks (again!): glad to see your are still going strong i 2022 :)

**Comment by mebeim** [comment]
Hey there @edelans! Thanks, glad to see you keep enjoying my repo. This year's gonna be tough since I'm busier than previous years with work, let's see how much I can postpone the burnout :')

**Comment by edelans** [comment]
eheh, I'm in the same boat, I've just joined a startup 3w ago, not sure how long I'll last!
