### ISSUE TITLE
Day 23, build_list , index out of bounds error

### ISSUE THREAD

**Issue by Hemadityamalla** [mebeim/aoc#6]
Hi Marco,This is my first time participating in the AOC and I'm learning how to code. I found your problem walkthroughs immensely helpful. I like how you explain the logic and the code simultaneously. 

Issue with the *build_list* function in the line below:

```python
next_cup = [None] * len(cups)
```

This initializes a list of the size of cups (9 in our case). This means `next_cup` has indices going from 0 to 8. This gives the _index out of bounds _ error on line 9 of the day23.py script. 

When the input is _123487596_, the loop below 
```python
for prev, cur in zip(cups, cups[1:]):
		next_cup[prev] = cur
````
has `next_cup[9] = 6`. But since `next_cup` has indices only till 8, we get an _index out of bounds_ error. I have found a small work around for this issue in the code snippet below.

```python
def build_list(cups, n_nums = None):
    next_cup = [None]*(max(cups) + 1) #I add the +1 so that we dont have to use the 0 index
    for prev,cur in zip(cups, cups[1:]):
        next_cup[prev] = cur
    if n_nums is not None:
        #Below two lines add the extra, consecutive cups
        next_cup[cups[-1]] = len(next_cup) 
        next_cup += list(range(len(next_cup)+1, n_nums+2))
        next_cup[n_nums] = cups[0] #This line makes sure that the 'clockwise arrangement' rule is obeyed
        return next_cup
    next_cup[cups[-1]] = cups[0] #This line makes sure that the 'clockwise arrangement' rule is obeyed
    return next_cup 
```
I added comments where the changes have been made. This does not alter your logic, but just takes care of the above issue. It would be awesome if you can simplify the above correction :+1: 
Please let me know if I have made a mistake in the above issue.

Thanks!
Hema

**Comment by mebeim** [comment]
Thank you very much for taking the time to report the issue, explain it in detail and also propose a working solution! Your workaround seems correct to me, I can't see an obvious improvement that would make it more compact while still being simple to understand, so I've updated the code pretty much how you describe. Fixed in 05fb531f553baac624e30bea506b2e5a9334b3c2.
