### ISSUE TITLE
Day 19 walkthrough explanation is different than rule

### ISSUE THREAD

**Issue by SSteve** [mebeim/aoc#9]
In the walkthrough for Day 19, the example rule 0 is 1 2 | 2 3. But in the second paragraph after the example, it starts treating it as 1 2 | 1 3:

> this second option of rule 0 means "match a followed by b followed by a"

This should be "match b followed by b followed by a"

Also, the tree shows 1 2 | 1  3.

**Comment by mebeim** [comment]
Thank you for spotting this! Fixed in a6cc22672d86f5f29866b1e0eb5b1196eb71ab7b.
